osx_image: xcode10.2
language: objective-c
sudo: required
env:
  global:
    - PROJECT="AStore.xcworkspace"
    - SCHEME="AStore"
    - IOS_SDK="iphonesimulator12.2"
    - DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=12.2"
  
install:
  - swift --version

before_script:
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
  - pod install

script:
  - set -o pipefail
  - xcodebuild clean build
    -workspace "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$IOS_SDK"
    -destination "$DESTINATION"
    -configuration Debug
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c